"""Create user, forgot_password, and user_access tables

Revision ID: a1b2c3d4e5f6
Revises: 8b956ff7441a
Create Date: 2025-04-11 22:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '8b956ff7441a'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table('users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=True),
        sa.Column('verified', sa.Boolean(), nullable=True),
        sa.Column('verification_token', sa.String(), nullable=True),
        sa.Column('login_attempts', sa.Integer(), nullable=True),
        sa.Column('block_expires', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)

    # Create forgot_passwords table
    op.create_table('forgot_passwords',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('verification_token', sa.String(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=True),
        sa.Column('ip_request', sa.String(), nullable=True),
        sa.Column('browser_request', sa.String(), nullable=True),
        sa.Column('country_request', sa.String(), nullable=True),
        sa.Column('ip_changed', sa.String(), nullable=True),
        sa.Column('browser_changed', sa.String(), nullable=True),
        sa.Column('country_changed', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_forgot_passwords'))
    )
    op.create_index(op.f('ix_forgot_passwords_email'), 'forgot_passwords', ['email'], unique=False)
    op.create_index(op.f('ix_forgot_passwords_verification_token'), 'forgot_passwords', ['verification_token'], unique=True)

    # Create user_access table
    op.create_table('user_access',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('ip', sa.String(), nullable=True),
        sa.Column('browser', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('access_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user_access'))
    )
    op.create_index(op.f('ix_user_access_email'), 'user_access', ['email'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop user_access table and indexes
    op.drop_index(op.f('ix_user_access_email'), table_name='user_access')
    op.drop_table('user_access')

    # Drop forgot_passwords table and indexes
    op.drop_index(op.f('ix_forgot_passwords_verification_token'), table_name='forgot_passwords')
    op.drop_index(op.f('ix_forgot_passwords_email'), table_name='forgot_passwords')
    op.drop_table('forgot_passwords')

    # Drop users table and indexes
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ### 